modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"

[[mods]]
modId = "liaveres"
version = "${file.jarVersion}"
displayName = "LiaVeres"
authors = "AlgorithmLX"
description = ''''''

[[dependencies.liaveres]]
modId = "forge"
mandatory = true
versionRange = "[43,)"

[[dependencies.liaveres]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"

[[dependencies.liaveres]]
modId = "curios"
mandatory = false
versionRange = "[1.19.2-1.1.0,)"

[[dependencies.liaveres]]
modId = "liquid"
mandatory = true
versionRange = "[1.19.2_1.0.0,1.19.2_1.1.0)"
