package com.algorithmlx.liaveres.api.config;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@Retention(RetentionPolicy.RUNTIME)
public @interface Config {
    String branch() default "common";
    String comment() default "automatically generated by liquid core";
    String name() default "";
}
