package com.algorithmlx.api.config;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@Retention(RetentionPolicy.RUNTIME)
public @interface Config {
    String branch() default "common";
    String comment() default "automatically generated by liquid core";
    String name() default "";
    Range range() default @Range(enableRanges = false);

    @interface Range {
        int minInt() default 0;
        int maxInt() default 0;
        float minFloat() default 0;
        float maxFloat() default 0;
        double minDouble() default 0;
        double maxDouble() default 0;
        long minLong() default 0;
        long maxLong() default 0;
        byte minByte() default 0;
        byte maxByte() default 0;
        short minShort() default 0;
        short maxShort() default 0;

        boolean enableRanges();
    }
}
